<?php

define('COREPATH',  'core'.DIRECTORY_SEPARATOR);
define('VIEWSPATH',  'views'.DIRECTORY_SEPARATOR);
define('CONTROLLERPATH',  'controller'.DIRECTORY_SEPARATOR);
define('MODELSPATH',  'models'.DIRECTORY_SEPARATOR);
define('ICONSPATH',  'src'.DIRECTORY_SEPARATOR.'icons'.DIRECTORY_SEPARATOR);
define('IMAGESPATH',  'src'.DIRECTORY_SEPARATOR.'images'.DIRECTORY_SEPARATOR);
define('DOCUMENTSPATH',  'src'.DIRECTORY_SEPARATOR.'documents'.DIRECTORY_SEPARATOR);